import Head from "next/head";
import Sidebar from "../components/Sidebar";
import Center from "../components/Center";
import { useEffect } from "react";
import Router from "next/router";
import { getSession, useSession } from "next-auth/react";
import Player from "../components/Player";
export default function Home() {
  const { data, status } = useSession();
  useEffect(() => {
    if (status !== "loading" && !data) {
      Router.push("/login");
    }
  }, [status, data]);
  return (
    <div className="bg-black h-screen overflow-hidden ">
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <Sidebar />
        <Center />
      </main>
      <div className="absolute bottom-0 w-full bg-red-500 ">
        <Player />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
